### ISSUE TITLE
Create simbricks.orchestration python package 

### ISSUE THREAD

**Issue by FreakyPenguin** [simbricks/simbricks#14]
As we clean up the SimBricks code for a release we should move the things currently in the `simbricks` package in the `experiments` folder into a `simbricks.orchestration` package to avoid namespace conflicts with future editions. E.g. for another project I built some simple python bindings for implementing pcie device simulators, and I imagine we'll want other similar separate packages in the SimBricks ecosystem over time. So we should rename this sooner rather than later.

**Comment by Kaufi-Jonas** [comment]
Here is what I plan to do. Did I understand you correctly?
```
mv experiments/ simbricks
mv simbricks/simbricks/ simbricks/orchestration
```

**Comment by FreakyPenguin** [comment]
@Kaufi-Jonas I'm not 100% percent sure what the right thing to do is longer term in terms of the full directory structure. In the short term what matters is just the python package namespace structure as that will require others to change their experiment scripts if we modify it.

For now I'd suggest keeping the experiment directory as there is a bunch of other things in there.  So basically this:
```
mkdir experiments/simbricks/orchestration
mv experiments/simbricks/* experiments/simbricks/orchestration/
```
And then also make sure that this is updated for all scripts with import (which unfortunately also includes the experiment scripts etc.)

Longer term we maybe want a `py` or `python` toplevel directory where the orchestration package and other packages go. But then we also need to find somewhere to put the experiment scripts etc.
