### ISSUE TITLE
Error building external simulators in VS Code dev containder

### ISSUE THREAD

**Issue by kevinyuan** [simbricks/simbricks#27]
Dear Simbricks team,

I saw this error when building external simulators, can you help to figureout what's the solution? Thanks.

-------------

simbricks@1914374f6809:/workspaces/simbricks$ make -j12 external
cd sims/external/gem5 && scons build/X86/gem5.fast \
        CCFLAGS="-I/workspaces/simbricks/lib" \
        LIBPATH="/workspaces/simbricks/lib" \
    -j`nproc`
cd sims/external/qemu && ./configure \
    --target-list=x86_64-softmmu \
    --disable-werror \
    --extra-cflags="-I/workspaces/simbricks/lib" \
    --extra-ldflags="-L/workspaces/simbricks/lib" \
    --enable-simbricks \
    --enable-simbricks-pci && \
  make
cd sims/external/ns-3 && COSIM_PATH=/workspaces/simbricks ./cosim-build.sh configure
/bin/sh: 1: ./configure: not found
make: *** [sims/external/rules.mk:47: sims/external/qemu/ready] Error 127
make: *** Waiting for unfinished jobs....
/bin/sh: 1: ./cosim-build.sh: not found
make: *** [sims/external/rules.mk:68: sims/external/ns-3/ready] Error 127

scons: *** No SConstruct file found.
File "/usr/lib/python3/dist-packages/SCons/Script/Main.py", line 947, in _main
make: *** [sims/external/rules.mk:36: sims/external/gem5/ready] Error 2

**Comment by Kaufi-Jonas** [comment]
Hi @kevinyuan,

I guess you are trying to build the external simulators inside the VS Code dev container? To me this looks like you haven't initialized the necessary sub-modules for the external simulators yet. Does executing `git submodule update --init` fix your issue?

**Comment by kevinyuan** [comment]
Thanks Kaufi, I am now able to run "make -j12 external" without any error.

One more question, can I actually run this command and subsequent "make -jN build-image" command from the host but not inside the container? Will that improve the compile speed ?

Thanks.

**Comment by FreakyPenguin** [comment]
@kevinyuan Could you let us know if this fixes your issue?

**Comment by kevinyuan** [comment]
Yes the issue is resolved by following your instruction.

Thanks very much.


Thanks.

Kevin Yuan


在 2022年8月23日，17:33，Antoine Kaufmann ***@***.***> 写道：

﻿

@kevinyuan<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkevinyuan&data=05%7C01%7C%7C61b49ef587da4ff6dccd08da84ea81a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637968439972597143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hedKIDB%2BcIBnQ1C8wPlcr0WNTxcZ3GuemLIHkVLp%2FMI%3D&reserved=0> Could you let us know if this fixes your issue?

**Comment by FreakyPenguin** [comment]
Excellent, thanks for confirming. PR #28 will also clear this up in the readme for future reference. :-)

Glad we were able to help.

Cheers
