### ISSUE TITLE
Qeustions about Simbricks emulating ARM CPU

### ISSUE THREAD

**Issue by nanmuxx** [simbricks/simbricks#34]
Can I change the ISA on the GEM5 emulated node from x86 to ARM? Does this involve changes in the Linux and softwares running on Gem5 nodes in SimBricks? Is it feasible and is it a big change?

**Comment by hajeongee** [comment]
Hi @nanmuxx  
There shouldn't be any problem with changing x86 to ARM. Then you might need a different ubuntu iso image and gem5 configuration script. It should be doable without big changes. Regarding gem5 script for using ARM processor, you can refer to `gem5/configs/example/fs.py` and `gem5/configs/common/FSConfigs.py` files.

**Comment by FreakyPenguin** [comment]
Hey @nanmuxx. As @hajeongee says, from the SimBricks side there is nothing stopping you from running gem5 (or qemu for that matter) with ARM or other architectures. The tricky bit with those is that unlike x86 the system configurations (for ARM especially) are much less standardized. How much work this is will reallly depend on what you are trying to do. I would suggest looking at gem5's documentation to see what ARM boards they have configurations for. If you want to use the SimBricks PCIe adapter you'll need a board/platform with PCI support. Not really sure what the status on the gem5-front is here. A bit more detail might help us asses how much work what you want to do might be.

**Comment by nanmuxx** [comment]
Thanks. I found the location where you specified the disk image in GEM5, in the `Class Gem5Host(HostSim)` of `Simbricks \ Experiments \ Simbricks \ Simulators.py`.
But I don't know what `--disk-image={env.cfgtar_path(self)}` means. What does the `cfg.{sim.name}.tar` stand for?

**Comment by FreakyPenguin** [comment]
We add two separate disks to our machine. One is the normal system disk (that's the one that's in qcow format). We then also add a second disk that we use for "specializing" the system for each experiment (so we don't have to generate different system disks). This is a bit hacky, but basically the python runtime will generate a tar file for each experiment. The tar contains a shell script with the commands to run the experiment, including initialization steps such as loading drivers or setting IP addresses. Additionally the tar can also include other experiment-specfic files (e.g. config files or in case of Corundum we also include the driver kernel module). We then directly specify this tar as a raw disk image for the second disk in the host. In the host this shows up as `/dev/sdb`, and the init script we use then just untars this to `/tmp/guest` and runs the script in there. `env.cfgtar_path(self)` will return the path for the tar for the experiment that's your're trying to run.

I hope this answers your question.

**Comment by nanmuxx** [comment]
I have started the simulation of an ARM system in gem5.  The disk image I specified is an ubuntu operating system, but the applications are not loaded.  I followed "/simbricks/images/rules. mk", and try to make a disk image which is installed applications, but didn't make it.  If I want to make a disk image on an x86 host for an ARM system in gem5 with the operating system and installed applications, is there a recommended way to do this?  If I use packer and qemu to build an ARM disk image, should I use packer_1.7.0_linux_arm64 and qemu-system-aarch64 instead of their x86 version?

**Comment by FreakyPenguin** [comment]
I have no experience with building system images for ARM at all. But a quick google search brings up this template in the packer example repo: https://github.com/mcandre/packer-templates/blob/issue-153/debian/debian-arm64.json (line 50 in particular seems to be one of the essential parts: `"qemu_binary": "qemu-system-aarch64"` also note that in the ARM world you will have to pick an appropriate board for your purposes.

If you are running on an x86 host you definitely still need the x86 version for packer, as ARM binaries will not run on x86. Just make sure you have built/installed `qemu-system-aarch64` on your host system.

**Comment by nanmuxx** [comment]
@FreakyPenguin Thanks very much. I'll try this too. 

I found a way to do this earlier by directly downloading the ARM linux image provided by gem5, mounting the image locally, then using qemu-system-aarch64 to chroot and installing my application on it. By reference to gem5/configs/example/fs.py and gem5/configs/common/FSConfigs.py files, I have modified the /gem5/configs/simbricks/simbricks.py file. Now I can launch the modified ARM image using simbricks.py in gem5 and test that the application has been installed successfully. But when I run the gem-i40e-pair script, the output is stuck with "gem5-i40e-pair: waiting for hosts to terminate". Here is the log:


gem5-i40e-pair: starting host.server.0
gem5-i40e-pair: starting host.client.0
host.client.0 ERR: ['warn: CheckedInt already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.client.0 ERR: ['warn: Enum already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.client.0 ERR: ['warn: ScopedEnum already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.server.0 ERR: ['warn: CheckedInt already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.server.0 ERR: ['warn: Enum already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.server.0 ERR: ['warn: ScopedEnum already exists in allParams. This may be caused by the Python 2.7 compatibility layer.']
host.client.0 OUT: ['Global frequency set at 1000000000000 ticks per second']
host.server.0 OUT: ['Global frequency set at 1000000000000 ticks per second']
host.client.0 ERR: ['warn: No dot file generated. Please install pydot to generate the dot file and pdf.']
host.client.0 ERR: ['warn: DRAM device capacity (32768 Mbytes) does not match the address range assigned (8192 Mbytes)']
host.client.0 ERR: ['info: kernel located at: /simbricks/images/image_download/binaries/vmlinux.arm64']
host.server.0 ERR: ['warn: No dot file generated. Please install pydot to generate the dot file and pdf.']
host.server.0 ERR: ['warn: DRAM device capacity (32768 Mbytes) does not match the address range assigned (8192 Mbytes)']
host.server.0 ERR: ['info: kernel located at: /simbricks/images/image_download/binaries/vmlinux.arm64']
host.client.0 ERR: ['warn: Highest ARM exception-level set to AArch32 but the workload is for AArch64. Assuming you wanted these to match.']
host.server.0 ERR: ['warn: Highest ARM exception-level set to AArch32 but the workload is for AArch64. Assuming you wanted these to match.']
host.server.0 ERR: ['warn: Sockets disabled, not accepting vnc client connections']
host.server.0 ERR: ['warn: Sockets disabled, not accepting terminal connections']
host.client.0 ERR: ['warn: Sockets disabled, not accepting vnc client connections']
host.client.0 ERR: ['warn: Sockets disabled, not accepting terminal connections']
host.server.0 ERR: ['warn: Sockets disabled, not accepting gdb connections']
host.client.0 ERR: ['warn: Sockets disabled, not accepting gdb connections']
host.server.0 ERR: ['info: Using bootloader at address 0x10']
host.server.0 ERR: ['info: Using kernel entry physical address at 0x80080000']
host.server.0 ERR: ['info: Loading DTB file: /simbricks/images/image_download/armv8_gem5_v1_1cpu.dtb at address 0x88000000']
host.server.0 ERR: ['warn: Existing EnergyCtrl, but no enabled DVFSHandler found.']
host.server.0 ERR: ['info: Entering event queue @ 0.  Starting simulation...']
host.server.0 ERR: ['warn: SCReg: Access to unknown device dcc0:site0:pos0:fn7:dev0']
host.client.0 ERR: ['info: Using bootloader at address 0x10']
host.client.0 ERR: ['info: Using kernel entry physical address at 0x80080000']
host.client.0 ERR: ['info: Loading DTB file: /simbricks/images/image_download/armv8_gem5_v1_1cpu.dtb at address 0x88000000']
host.client.0 ERR: ['warn: Existing EnergyCtrl, but no enabled DVFSHandler found.']
host.client.0 ERR: ['info: Entering event queue @ 0.  Starting simulation...']
host.client.0 ERR: ['warn: SCReg: Access to unknown device dcc0:site0:pos0:fn7:dev0']
gem5-i40e-pair: started host.server.0
gem5-i40e-pair: started host.client.0
gem5-i40e-pair: waiting for hosts to terminate


Because of `host.server.0 ERR: ['warn: Sockets disabled, not accepting terminal connections']`, I suspect that gem5 cannot connect to port 3456 of system.terminal, but I don't know where the error is. Do you know why?

**Comment by FreakyPenguin** [comment]
The sockets thing is unrelated to your error, I think. At a quick glance this looks like your gem5 was built without SimBricks support. If scons does not find the simbricks headers or libraries it will disable simbricks support in the build (scons should also log the features enabled and disabled iirc).

I can think of two possible causes off the top of my head:
1) You are not using our modified gem5 repo (https://github.com/simbricks/gem5).
2) You are not passing in the required arguments for scons to find the SimBricks libraries. For those have a look at the makefile in the simbricks repo: https://github.com/simbricks/simbricks/blob/main/sims/external/rules.mk#L35-L39 (alternatively you can also just clone the code to `sims/external/gem5` and then build with `make 
-jN sims/external/gem5/ready`)

**Comment by FreakyPenguin** [comment]
The sockets messages are just warnings and would just affect the ability to connect to the interactive terminal/VNC/gdb. I don't remember off the top of my head why they are disabled. If you want to use the interactive terminal you would need to dig in a bit and see why they are disabled. I've used the interactive terminl and gdb with gem5, but that was a long time ago.

The "waiting for hosts to terminate" message is normal. That's just the orchestration framework indicating that it has now started everyting and is waiting for the experiment to finish.

Did you check if gem5 is stuck or could it just be slow? If you send the gem5 an USR1 signal it should print out the current simulation time stamp. So if you do that twice you should see if time is advancing.

The warnings about unknown device accesses may or may not be problems, worth quickly looking into what should be there.

**Comment by nanmuxx** [comment]
Thanks! I am using the modified gem5 repo (https://github.com/simbricks/gem5). I cloned the code to sims/external/gem5 and modified the makefile https://github.com/simbricks/simbricks/blob/main/sims/external/rules.mk#L35-L39  like this:

$(d)gem5/ready: $(d)gem5
    +cd $< && scons build/ARM/gem5.$(GEM5_VARIANT) \
        CCFLAGS="-I$(abspath $(lib_dir))" \
        LIBPATH="$(abspath $(lib_dir))" \
        -j`nproc`

Then I built gem5.opt with make sims/external/gem5/ready. Is there anything wrong?

I can now see the gem5 startup information and exit triggered by the m5_exit directive, but target's Linux startup process is not printed. What could possibly be causing this? The log is down here：

gem5-i40e-pair: waiting for hosts to terminate
host.client.0 ERR: ['warn: Existing EnergyCtrl, but no enabled DVFSHandler found.']
host.client.0 ERR: ['info: Entering event queue @ 1205427470480.  Starting simulation...']
host.client.0 ERR: ['warn: PowerState: Already in the requested power state, request ignored']
host.client.0 ERR: ['warn: User mode does not have SPSR']
host.client.0 ERR: ['warn: User mode does not have SPSR']
host.client.0 ERR: ['info: Entering event queue @ 1205427480480.  Starting simulation...']
host.client.0 ERR: ["warn: \tinstruction 'csdb' unimplemented"]
host.client.0 OUT: ['gem5 Simulator System.  http://gem5.org']
host.client.0 OUT: ['gem5 is copyrighted software; use the --copyright option for details.']
host.client.0 OUT: ['']
host.client.0 OUT: ['gem5 version 20.0.0.1']
host.client.0 OUT: ['gem5 compiled Nov  9 2022 08:25:51']
host.client.0 OUT: ['gem5 started Nov 22 2022 08:56:39']
host.client.0 OUT: ['gem5 executing on 4f790fc6a08c, pid 1118191']
host.client.0 OUT: ['command line: /simbricks/sims/external/gem5/build/ARM/gem5.opt --outdir=/simbricks/experiments/out/gem5-i40e-pair/1/gem5-out.client.0 /simbricks/sims/external/gem5/configs/simbricks/simbricks.py --caches --l2cache --l3cache --l1d_size=32kB --l1i_size=32kB --l2_size=2MB --l3_size=32MB --l1d_assoc=8 --l1i_assoc=8 --l2_assoc=4 --l3_assoc=16 --cacheline_size=64 --cpu-clock=8GHz --sys-clock=1GHz --checkpoint-dir=/simbricks/experiments/out/gem5-i40e-pair/0/gem5-cp.client.0 --bootloader=/simbricks/images/image_download/boot.arm64 --kernel=/simbricks/images/image_download/binaries/vmlinux.arm64 --disk-image=/simbricks/images/image_download/ubuntu-18.04-arm64-docker.img --disk-image=/simbricks/experiments/out/gem5-i40e-pair/1/cfg.client.0.tar --dtb=/simbricks/images/image_download/armv8_gem5_v1_1cpu.dtb --cpu-type=TimingSimpleCPU --mem-size=8192MB --num-cpus=1 --ddio-enabled --ddio-way-part=8 --mem-type=DDR4_2400_16x4 -r 1 --simbricks-pci=connect:/simbricks/experiments/out/gem5-i40e-pair/1/dev.pci.client.0.:latency=500ns:sync_interval=500ns:sync']
host.client.0 OUT: ['']
host.client.0 OUT: ['info: Standard input is not a terminal, disabling listeners.']
host.client.0 OUT: ['CEHCKPOINT RESTORE THINGIE']
host.client.0 OUT: ['Switch at curTick count:10000']
host.client.0 OUT: ['Switched CPUS @ tick 1205427480480']
host.client.0 OUT: ['switching cpus']
host.client.0 OUT: ['**** REAL SIMULATION ****']
host.client.0 OUT: ['Exiting @ tick 12286539799250 because m5_exit instruction encountered']
host.client.0 TERMINATED: 0

**Comment by jonas-kaufmann** [comment]
Hey @nanmuxx, I'm closing this for now but feel free to reopen if you have follow-up questions.
