### ISSUE TITLE
Pin linter versions?

### ISSUE THREAD

**Issue by FreakyPenguin** [simbricks/simbricks#52]
Currently our pipline fails because there seems to be a new warning appearing in code not even touched by any of the commits. https://github.com/simbricks/simbricks/actions/runs/4157857585/jobs/7192655212

**Comment by jonas-kaufmann** [comment]
Happened again for https://github.com/simbricks/simbricks/actions/runs/9101921726/job/25020306008?pr=116

I'm going to take care of this now.
