### ISSUE TITLE
Could not find libsimbricks to install

### ISSUE THREAD

**Issue by HoaNguyen55** [simbricks/simbricks#91]
## Issue Description:
Dear team, I downloaded the Simbricks source code, but when I compiled code to build QEMU, the error happened. It informs that install libsimbricks, but I don't how to find and install it.
## Issue Description:
```
ken@ken-pc:~/Documents/simbricks$ make -j10 sims/external/qemu/ready
cd sims/external/qemu && ./configure \
    --target-list=x86_64-softmmu \
    --disable-werror \
    --with-pkgversion=SimBricks \
    --extra-cflags="-I/home/hoaaa123/Documents/simbricks/lib" \
    --extra-ldflags="-L/home/hoaaa123/Documents/simbricks/lib" \
    --enable-simbricks \
    --enable-simbricks-pci && \
  make
Using './build' as the directory for build output

ERROR: User requested feature simbricks
       configure was not able to find it.
       Install libsimbricks devel

make: *** [sims/external/rules.mk:55: sims/external/qemu/ready] Error 1
```
## Possible Solution:
It seems that the libsimbricks devel package is required but not found.

**Comment by q713** [comment]
Hey,
did you compile the core simbricks library beforehand?
To compile the core SimBricks components simply run `make -jN` (replace N with the number of cores you may want to use). 
In case you need  Verilator or Rdma support you need to additionally enable those by setting ENABLE_VERILATOR=y ENABLE_RDMA=y on the make command-line or by creating mk/local.mk and inserting those settings there.

After you build the core simbricks library `make -jN sims/external/qemu/ready` should normally work.

Let me know if that solves you problem.

Cheers,
Jakob

**Comment by HoaNguyen55** [comment]
Oh, it's my fault, I met a lot of problem because of missing library and I decided to ignore this step. I will go on debugging.
Thank you for your comment.
Hoa
