### ISSUE TITLE
Could not boot virtual machine QEMU x86_64

### ISSUE THREAD

**Issue by HoaNguyen55** [simbricks/simbricks#92]
## Description:
Dear team, I could not find initrd image to be able boot QEMU, also what is "root=" mean. I try:
root=/dev/hda or 
root=/dev/sdb or 
root=/dev/sda 
They don't work.

## Issue:
```
[    1.186938] sr 1:0:0:0: Attached scsi generic sg0 type 5
[    1.190683] RAMDISK: Couldn't find valid RAM disk image starting at 0.
[    1.197213] **VFS: Cannot open root device "sda2" or unknown-block(0,0): error -6**
[    1.197619] **Please append a correct "root=" boot option; here are the available partitions:**
[    1.198029] 0100           16384 ram0 
[    1.198100]  (driver?)
[    1.198358] 0101           16384 ram1 
[    1.198369]  (driver?)
[    1.198663] 0102           16384 ram2 
[    1.198672]  (driver?)
[    1.198996] 0103           16384 ram3 
[    1.199006]  (driver?)
[    1.199232] 0104           16384 ram4 
[    1.199239]  (driver?)
[    1.199509] 0105           16384 ram5 
[    1.199519]  (driver?)
[    1.199754] 0106           16384 ram6 
[    1.199762]  (driver?)
[    1.199982] 0107           16384 ram7 
[    1.199989]  (driver?)
[    1.200205] 0108           16384 ram8 
[    1.200212]  (driver?)
[    1.200486] 0109           16384 ram9 
[    1.200495]  (driver?)
[    1.201167] 010a           16384 ram10 
[    1.201175]  (driver?)
[    1.201420] 010b           16384 ram11 
[    1.201427]  (driver?)
[    1.201718] 010c           16384 ram12 
[    1.201729]  (driver?)
[    1.201993] 010d           16384 ram13 
[    1.202001]  (driver?)
[    1.202309] 010e           16384 ram14 
[    1.202324]  (driver?)
[    1.205942] 010f           16384 ram15 
[    1.206035]  (driver?)
[    1.206754] 0b00         1048575 sr0 
[    1.206887]  driver: sr
[    1.207598] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    1.208315] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.15.93 #1
[    1.208979] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org 04/01/2014
[    1.209788] Call Trace:
[    1.210414]  <TASK>
[    1.210704]  dump_stack_lvl+0x34/0x44
[    1.211263]  panic+0xee/0x293
[    1.211406]  mount_block_root+0x1da/0x1da
[    1.211638]  ? mount_root+0x4f/0x177
[    1.211776]  prepare_namespace+0x131/0x160
[    1.211930]  ? rest_init+0xb6/0xb6
[    1.212078]  kernel_init+0x11/0x101
[    1.212212]  ret_from_fork+0x1f/0x30
[    1.212390]  </TASK>
[    1.212859] Kernel Offset: disabled
[    1.213217] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---
```

## Procedure:
At simbricks folder, do these steps:
1. Compile Simbricks: ```make -j12```
2. Compile QEMU: ```make -j12 sims/external/qemu/ready```
3. Compile build-image-min: ```make -j12 build-images-min```
4. Run QEMU: ```./sims/external/qemu/build/qemu-system-x86_64 -kernel images/bzImage -initrd images/kernel/config-5.15.93 -nographic -append "console=tty1 console=ttyS0 images/m5 images/kheaders.tar.bz2"

I don't know "root=" meaning and where I can find "initrd" image. Please also help to review my command line to run qemu-system-x86_64. I found these parameter when step 3 running, I assume these could work.

Thank you,
Hoa

**Comment by HoaNguyen55** [comment]
[build-img-min.log](https://github.com/simbricks/simbricks/files/14802629/build-img-min.log)
Here is a log file when I run QEMU.

**Comment by FreakyPenguin** [comment]
Hi @HoaNguyen55!

I do not understand what you are trying to do here... Our kernel is built so it does not need an initrd at all, to get things booting as quickly as possible with slower simulators. And what root= you have to specify depends on what you put on your qemu command line, since you put that together yourself. Those things have nothing to do with SimBricks at all, and if you just want to run a QEMU emulation/VM, the qemu documentation should be your starting point.

What are you trying to do? The only reason you would manually have to run QEMU with SimBricks is if you are trying to do something very special... Our supported way is to go through the SimBricks orchestration framework, which will take care of running each simulator etc, based on the simulation python configuration script you provide. There is a load of example scripts for that in the repo. I would  suggest you start by looking at the SimBricks documentation: https://simbricks.readthedocs.io/en/latest/user/quickstart.html

If you have something you are trying to do that's not covered there or that's unclear, we are, of course happy to help.

**Comment by HoaNguyen55** [comment]
In section 2.1.1 of the Simbricks documentation, Host0 currently employs gem5, while Host1 and Host2 utilize QEMU. However, I propose transitioning Host0 from the gem5 simulator system to QEMU. This adjustment is necessary since NIC0 (Corundum) has already been integrated via Simbricks PCIe interface. Additionally, this change will ensure a synchronous environment. Hence, I anticipate that QEMU will operate effectively post-image and kernel compilation. 

Hope you can understand what I'm trying to do. 

Thank you so much,
Hoa

**Comment by HoaNguyen55** [comment]
For those who need to run QEMU with Simbricks device could be considered with this command line to run:
```
<path to simbricks>/sims/external/qemu/build/x86_64-softmmu/qemu-system-x86_64 -machine q35 -serial mon:stdio -cpu Skylake-Server -display none -nic none -kernel <path to simbricks>/images/bzImage -drive file=<path to simbricks>/experiments/out/iperf-qemu-i40e-pair/1/hdcopy.server.0,if=ide,index=0,media=disk -drive file=<path to simbricks>/experiments/out/iperf-qemu-i40e-pair/1/cfg.server.0.tar,if=ide,index=1,media=disk,driver=raw -append earlyprintk=ttyS0 console=ttyS0 root=/dev/sda1 init=/home/ubuntu/guestinit.sh rw -m 512 -smp 1 -icount shift=-2,sleep=off -device simbricks-pci,socket=<path to simbricks>/experiments/out/iperf-qemu-i40e-pair/1/dev.pci.server.0.,sync=on,pci-latency=500,sync-period=500
```
